const API_KEY = `28073605-eb5bbf72074ca81ce4c12ce79`;
const API_NAME = "Pixabay API";

const INITIAL_RATE_LIMIT = 6;

const TIMEOUT_RATE = 500; //Debouncing Time

const INITIAL_CATEGORY = "food";

const LOGO_TITLE = "Bhurtel Pics"

const INITIAL_LOADING_TIME = 1000;

export { API_NAME , API_KEY , INITIAL_RATE_LIMIT ,INITIAL_CATEGORY , LOGO_TITLE , TIMEOUT_RATE , INITIAL_LOADING_TIME}